services:
    csa_guzzle.data_collector.history_bag:
        class: Csa\GuzzleHttp\Middleware\History\History
        public: true

    csa_guzzle.data_collector.guzzle:
        class: Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector
        arguments:
            - ~
            - '@csa_guzzle.data_collector.history_bag'
        tags:
            - { name: data_collector, template: '@CsaGuzzle/Collector/guzzle.html.twig', id: guzzle }
